language: c

before_install:
    - bash install.sh

script:
    - bash build.sh

notifications:
    on_failure: change
    on_success: change

cache: 
    directories:
        - cache
    apt: true

env:
    - OPENRCT2_CMAKE_OPTS=
    - OPENRCT2_CMAKE_OPTS="-DDISABLE_NETWORK=ON"

sudo: required

services:
    - docker
